services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    ports:
      - "9200:9200"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "false"
      ELASTIC_PASSWORD: "elastic" 
    healthcheck:
      test: curl -u elastic:elastic http://elasticsearch:9200
      interval: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: "user123"
      ELASTICSEARCH_PASSWORD: "elastic"
    depends_on:
      elasticsearch:
        condition: service_healthy
  elastic-search-service:
    build: ./elastic-search-service
    ports: 
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      
volumes:
  esdata:
    driver: local
