server:
  port: 9000

constants:
  media-path: /data/media/
  posts-topic: posts-topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    header: "Authorization"
    key: jxgEQeXA28P32q8AVdbyk1ASDANdu8553YUn4

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/post-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    default-schema: public
    baseline-on-migrate: true
  application:
    name: post-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      flywaydb: DEBUG
